// Each lesson links one glossary term to a worked example and a separate practice question.
const codeLessons = [
  {
    id: "variable",
    deckId: "variables-values",
    term: "Переменная",
    exampleCode: 'int score = 4;\nConsole.WriteLine(score);',
    exampleResult: "4",
    exampleNote: "Имя score позволяет обратиться к сохранённому числу позже.",
    kind: "Что выведет код?",
    challengeCode: 'int lives = 3;\nConsole.WriteLine(lives);',
    prompt: "Что появится в консоли?",
    options: ["3", "lives", "int", "Ничего"],
    correctIndex: 0,
    explanation: "В lives хранится число 3. Console.WriteLine выводит значение переменной, а не её имя."
  },
  {
    id: "initialization",
    deckId: "variables-values",
    term: "Инициализация",
    exampleCode: 'string city = "Казань";\nConsole.WriteLine(city);',
    exampleResult: "Казань",
    exampleNote: "Первое значение задаётся сразу при объявлении переменной.",
    kind: "Найдите строку",
    challengeCode: 'int level;\nlevel = 2;\nConsole.WriteLine(level);',
    prompt: "В какой строке переменная level впервые получает значение?",
    options: ["В первой", "Во второй", "В третьей", "Значение не задано"],
    correctIndex: 1,
    explanation: "В первой строке переменная только объявлена. Первое присваивание происходит во второй строке."
  },
  {
    id: "assignment",
    deckId: "variables-values",
    term: "Присваивание",
    exampleCode: 'int points = 2;\npoints = 5;\nConsole.WriteLine(points);',
    exampleResult: "5",
    exampleNote: "Второе присваивание заменяет прежнее значение points.",
    kind: "Что выведет код?",
    challengeCode: 'int count = 1;\ncount = count + 2;\nConsole.WriteLine(count);',
    prompt: "Что появится в консоли?",
    options: ["1", "2", "3", "12"],
    correctIndex: 2,
    explanation: "Сначала count равен 1. Выражение count + 2 даёт 3, и это значение сохраняется в count."
  },
  {
    id: "int",
    deckId: "csharp-data-types",
    term: "int",
    exampleCode: 'int apples = 6;\nConsole.WriteLine(apples + 2);',
    exampleResult: "8",
    exampleNote: "int хранит целое число; здесь к нему прибавляется ещё 2.",
    kind: "Где ошибка?",
    challengeCode: 'int apples = "6";\nConsole.WriteLine(apples);',
    prompt: "Почему этот код не соберётся?",
    options: ["int нельзя выводить", "Строку нельзя напрямую присвоить int", "Имя apples запрещено", "После 6 нужна точка"],
    correctIndex: 1,
    explanation: "Кавычки делают «6» строкой. Для int нужно записать число без кавычек или явно преобразовать строку."
  },
  {
    id: "bool",
    deckId: "csharp-data-types",
    term: "bool",
    exampleCode: 'bool isReady = true;\nConsole.WriteLine(isReady);',
    exampleResult: "True",
    exampleNote: "bool хранит логическое значение true или false. В консоли оно выводится с прописной буквы.",
    kind: "Что выведет код?",
    challengeCode: 'bool isAdult = 17 >= 18;\nConsole.WriteLine(isAdult);',
    prompt: "Что появится в консоли?",
    options: ["True", "False", "17", "Ошибка компиляции"],
    correctIndex: 1,
    explanation: "17 не больше и не равно 18, поэтому сравнение даёт false; в консоли появится False."
  },
  {
    id: "string",
    deckId: "csharp-data-types",
    term: "string",
    exampleCode: 'string word = "код";\nConsole.WriteLine(word + "ер");',
    exampleResult: "кодер",
    exampleNote: "Оператор + соединяет две строки в одну.",
    kind: "Что выведет код?",
    challengeCode: 'string first = "C";\nstring second = "#";\nConsole.WriteLine(first + second);',
    prompt: "Что появится в консоли?",
    options: ["C#", "C #", "firstsecond", "Ошибка компиляции"],
    correctIndex: 0,
    explanation: "Строки соединяются без пробела: «C» + «#» даёт «C#»."
  },
  {
    id: "decimal",
    deckId: "csharp-data-types",
    term: "decimal",
    exampleCode: 'decimal price = 12.5m;\nConsole.WriteLine(price > 10m);',
    exampleResult: "True",
    exampleNote: "Суффикс m обозначает литерал decimal. Сравнение даёт логический результат.",
    kind: "Где ошибка?",
    challengeCode: 'decimal price = 12.5;\nConsole.WriteLine(price);',
    prompt: "Почему этот код не соберётся?",
    options: ["Для decimal нужен суффикс m у литерала", "decimal нельзя выводить", "Дробные числа запрещены", "Имя price зарезервировано"],
    correctIndex: 0,
    explanation: "Литерал 12.5 без суффикса имеет тип double. Запишите 12.5m для decimal."
  },
  {
    id: "var",
    deckId: "typing-and-output",
    term: "var",
    exampleCode: 'var year = 2026;\nConsole.WriteLine(year);',
    exampleResult: "2026",
    exampleNote: "Компилятор определяет тип int по начальному значению. Тип переменной не меняется потом сам собой.",
    kind: "Где ошибка?",
    challengeCode: 'var count = 5;\ncount = "пять";',
    prompt: "Почему этот код не соберётся?",
    options: ["var нельзя применять с числами", "count уже имеет тип int", "count нельзя изменить", "Нужен Console.WriteLine"],
    correctIndex: 1,
    explanation: "По значению 5 компилятор определил тип int. Строку нельзя напрямую записать в int."
  },
  {
    id: "write-line",
    deckId: "typing-and-output",
    term: "Console.WriteLine",
    exampleCode: 'Console.WriteLine("Первая");\nConsole.WriteLine("Вторая");',
    exampleResult: "Первая\nВторая",
    exampleNote: "Каждый вызов выводит значение и переводит курсор на новую строку.",
    kind: "Что выведет код?",
    challengeCode: 'Console.WriteLine("A");\nConsole.WriteLine("B");',
    prompt: "Как будут расположены буквы в консоли?",
    options: ["A и B на одной строке", "A, затем B на новой строке", "Только B", "Ничего"],
    correctIndex: 1,
    explanation: "После каждого Console.WriteLine курсор переходит на новую строку."
  },
  {
    id: "interpolation",
    deckId: "typing-and-output",
    term: "Строковая интерполяция",
    exampleCode: 'int age = 18;\nConsole.WriteLine($"Возраст: {age}");',
    exampleResult: "Возраст: 18",
    exampleNote: "Знак $ разрешает вставить значение age внутрь строки через фигурные скобки.",
    kind: "Что выведет код?",
    challengeCode: 'string name = "Ира";\nConsole.WriteLine($"Привет, {name}!");',
    prompt: "Что появится в консоли?",
    options: ["Привет, Ира!", "Привет, {name}!", "Привет, name!", "Ошибка компиляции"],
    correctIndex: 0,
    explanation: "Знак $ включает интерполяцию: {name} заменяется значением переменной, то есть «Ира»."
  },
  {
    id: "read-line",
    deckId: "input-operations-conversions",
    term: "Console.ReadLine",
    exampleCode: 'string? name = Console.ReadLine();\nConsole.WriteLine($"Привет, {name}!");',
    exampleInput: "Мира",
    exampleResult: "Привет, Мира!",
    exampleNote: "Console.ReadLine читает введённый текст как строку. Знак ? допускает отсутствие ввода.",
    kind: "Что выведет код?",
    challengeCode: 'string? city = Console.ReadLine();\nConsole.WriteLine($"Город: {city}");',
    challengeInput: "Омск",
    prompt: "Что появится в консоли после ввода?",
    options: ["Город: Омск", "Город: city", "Омск: Город", "Ошибка компиляции"],
    correctIndex: 0,
    explanation: "Console.ReadLine вернёт строку «Омск», а интерполяция подставит её вместо {city}."
  },
  {
    id: "integer-division",
    deckId: "input-operations-conversions",
    term: "Целочисленное деление",
    exampleCode: 'Console.WriteLine(7 / 2);',
    exampleResult: "3",
    exampleNote: "Оба операнда целые, поэтому дробная часть результата отбрасывается.",
    kind: "Что выведет код?",
    challengeCode: 'Console.WriteLine(11 / 4);',
    prompt: "Что появится в консоли?",
    options: ["2", "2.75", "3", "Ошибка компиляции"],
    correctIndex: 0,
    explanation: "11 / 4 при целочисленном делении даёт 2. Дробная часть 0.75 отбрасывается."
  },
  {
    id: "remainder",
    deckId: "input-operations-conversions",
    term: "Остаток от деления",
    exampleCode: 'Console.WriteLine(7 % 2);',
    exampleResult: "1",
    exampleNote: "7 = 2 × 3 + 1, поэтому остаток равен 1.",
    kind: "Что выведет код?",
    challengeCode: 'Console.WriteLine(14 % 5);',
    prompt: "Что появится в консоли?",
    options: ["2", "4", "5", "14"],
    correctIndex: 1,
    explanation: "14 = 5 × 2 + 4. Оператор % возвращает остаток 4."
  },
  {
    id: "explicit-conversion",
    deckId: "input-operations-conversions",
    term: "Явное преобразование",
    exampleCode: 'double value = 4.8;\nint whole = (int)value;\nConsole.WriteLine(whole);',
    exampleResult: "4",
    exampleNote: "Приведение (int) отбрасывает дробную часть положительного числа.",
    kind: "Что выведет код?",
    challengeCode: 'double value = 9.9;\nConsole.WriteLine((int)value);',
    prompt: "Что появится в консоли?",
    options: ["9", "10", "9.9", "Ошибка компиляции"],
    correctIndex: 0,
    explanation: "При приведении 9.9 к int дробная часть отбрасывается, получается 9."
  },
  {
    id: "invalid-input",
    deckId: "input-operations-conversions",
    term: "Некорректный ввод",
    exampleCode: 'string? text = Console.ReadLine();\nif (int.TryParse(text, out int number))\n    Console.WriteLine(number);\nelse\n    Console.WriteLine("Введите число");',
    exampleInput: "кот",
    exampleResult: "Введите число",
    exampleNote: "TryParse проверяет ввод без исключения. Слово «кот» нельзя преобразовать в int.",
    kind: "Что выведет код?",
    challengeCode: 'string? text = Console.ReadLine();\nif (int.TryParse(text, out int number))\n    Console.WriteLine(number);\nelse\n    Console.WriteLine("Ошибка ввода");',
    challengeInput: "12кг",
    prompt: "Что появится в консоли после ввода?",
    options: ["12", "12кг", "Ошибка ввода", "Программа завершится с исключением"],
    correctIndex: 2,
    explanation: "Строка «12кг» целиком не является целым числом. TryParse вернёт false, поэтому выполнится ветка else."
  },
  {
    id: "lab6-equality",
    deckId: "conditions-logic",
    term: "Равенство ==",
    exampleCode: 'int score = 60;\nConsole.WriteLine(score == 60);',
    exampleResult: "True",
    exampleNote: "Два знака == сравнивают значения. Один знак = присваивает значение переменной.",
    kind: "Что выведет код?",
    challengeCode: 'int debts = 1;\nConsole.WriteLine(debts == 0);',
    prompt: "Что появится в консоли?",
    options: ["True", "False", "1", "Ошибка компиляции"],
    correctIndex: 1,
    explanation: "1 не равно 0, поэтому сравнение даёт false; Console.WriteLine выводит False."
  },
  {
    id: "lab6-and",
    deckId: "conditions-logic",
    term: "Логическое И &&",
    exampleCode: 'int score = 95;\nint debts = 1;\nbool hasAdmission = score >= 60 && debts == 0;\nConsole.WriteLine(hasAdmission);',
    exampleResult: "False",
    exampleNote: "Баллов хватает, но есть задолженность. Для && оба условия должны быть верны.",
    kind: "Что выведет код?",
    challengeCode: 'int score = 60;\nint debts = 0;\nConsole.WriteLine(score >= 60 && debts == 0);',
    prompt: "Есть ли допуск при этих значениях? Что выведет код?",
    options: ["True", "False", "60", "Ошибка компиляции"],
    correctIndex: 0,
    explanation: "60 достигает проходного балла, а задолженностей нет. Обе части && равны true."
  },
  {
    id: "lab6-or",
    deckId: "conditions-logic",
    term: "Логическое ИЛИ ||",
    exampleCode: 'int score = 95;\nint debts = 1;\nbool needsConsultation = score < 60 || debts > 0;\nConsole.WriteLine(needsConsultation);',
    exampleResult: "True",
    exampleNote: "Консультация нужна из-за задолженности. Для || достаточно одного верного условия.",
    kind: "Что выведет код?",
    challengeCode: 'int score = 60;\nint debts = 0;\nConsole.WriteLine(score < 60 || debts > 0);',
    prompt: "Нужна ли консультация по этим правилам? Что выведет код?",
    options: ["True", "False", "60", "Ошибка компиляции"],
    correctIndex: 1,
    explanation: "Баллы не меньше 60 и задолженностей нет. Обе части || ложны."
  },
  {
    id: "lab6-not",
    deckId: "conditions-logic",
    term: "Логическое НЕ !",
    exampleCode: 'bool hasDebts = false;\nConsole.WriteLine(!hasDebts);',
    exampleResult: "True",
    exampleNote: "Оператор ! превращает false в true: задолженностей нет.",
    kind: "Что выведет код?",
    challengeCode: 'bool hasDebts = true;\nConsole.WriteLine(!hasDebts);',
    prompt: "Что появится в консоли?",
    options: ["True", "False", "0", "Ошибка компиляции"],
    correctIndex: 1,
    explanation: "hasDebts равно true, а ! меняет значение на противоположное — false."
  },
  {
    id: "lab6-range",
    deckId: "conditions-logic",
    term: "Проверка диапазона",
    exampleCode: 'int score = 100;\nbool isValid = score >= 0 && score <= 100;\nConsole.WriteLine(isValid);',
    exampleResult: "True",
    exampleNote: "Границы включены: 0 и 100 — допустимые баллы.",
    kind: "Где ошибка?",
    challengeCode: 'int score = 75;\nbool isValid = 0 <= score <= 100;',
    prompt: "Почему этот код не соберётся?",
    options: ["Нужно записать две проверки и соединить их через &&", "75 выходит за диапазон", "bool нельзя присваивать результат", "Нужны круглые скобки вокруг 100"],
    correctIndex: 0,
    explanation: "В C# нельзя записывать цепочку 0 <= score <= 100. Правильно: score >= 0 && score <= 100."
  },
  {
    id: "lab6-constant",
    deckId: "conditions-logic",
    term: "Константа const",
    exampleCode: 'const int PassingScore = 60;\nConsole.WriteLine(59 >= PassingScore);',
    exampleResult: "False",
    exampleNote: "Проходной балл задан в одном месте и не меняется во время работы программы.",
    kind: "Где ошибка?",
    challengeCode: 'const int PassingScore = 60;\nPassingScore = 70;',
    prompt: "Почему этот код не соберётся?",
    options: ["Константе нельзя присвоить новое значение", "const нельзя использовать с int", "Имя должно быть строчными буквами", "После 70 не нужна точка с запятой"],
    correctIndex: 0,
    explanation: "Значение const задаётся при объявлении; строка PassingScore = 70 пытается изменить константу."
  },
  {
    id: "lab6-validation",
    deckId: "conditions-logic",
    term: "Проверка допустимости данных",
    exampleCode: 'int score = 101;\nint debts = 0;\nbool isValid = score >= 0 && score <= 100 && debts >= 0;\nif (isValid)\n{\n    Console.WriteLine("Данные приняты");\n}\nelse\n{\n    Console.WriteLine("Ошибка данных");\n}',
    exampleResult: "Ошибка данных",
    exampleNote: "Баллы 101 вне диапазона. Расчёты должны выполняться только в ветке допустимых данных.",
    kind: "Что выведет код?",
    challengeCode: 'int score = 75;\nint debts = -1;\nbool isValid = score >= 0 && score <= 100 && debts >= 0;\nConsole.WriteLine(isValid ? "Данные приняты" : "Ошибка данных");',
    prompt: "Что появится в консоли?",
    options: ["Данные приняты", "Ошибка данных", "75", "Ошибка компиляции"],
    correctIndex: 1,
    explanation: "Количество задолженностей отрицательно, поэтому isValid равно false."
  },
  {
    id: "lab6-if",
    deckId: "branching-menu",
    term: "if",
    exampleCode: 'int score = 59;\nif (score < 60)\n{\n    Console.WriteLine("Недостаточно баллов");\n}',
    exampleResult: "Недостаточно баллов",
    exampleNote: "Блок в фигурных скобках выполняется, потому что 59 < 60 равно true.",
    kind: "Что выведет код?",
    challengeCode: 'int score = 60;\nif (score < 60)\n{\n    Console.WriteLine("Консультация");\n}\nelse\n{\n    Console.WriteLine("Баллов достаточно");\n}',
    prompt: "Какую ветку выберет программа?",
    options: ["Консультация", "Баллов достаточно", "Обе ветки", "Ни одну"],
    correctIndex: 1,
    explanation: "Условие 60 < 60 ложно. Выполняется только блок else."
  },
  {
    id: "lab6-else-if",
    deckId: "branching-menu",
    term: "else if",
    exampleCode: 'int score = 75;\nif (score >= 90)\n{\n    Console.WriteLine(5);\n}\nelse if (score >= 75)\n{\n    Console.WriteLine(4);\n}\nelse\n{\n    Console.WriteLine(3);\n}',
    exampleResult: "4",
    exampleNote: "Первое условие ложно, второе верно. После него остальные ветки цепочки не проверяются.",
    kind: "Что выведет код?",
    challengeCode: 'int score = 74;\nif (score >= 90)\n{\n    Console.WriteLine(5);\n}\nelse if (score >= 75)\n{\n    Console.WriteLine(4);\n}\nelse if (score >= 60)\n{\n    Console.WriteLine(3);\n}',
    prompt: "Какая оценка появится в консоли?",
    options: ["5", "4", "3", "Ничего"],
    correctIndex: 2,
    explanation: "74 меньше 90 и 75, но не меньше 60. Выполняется третья ветка."
  },
  {
    id: "lab6-independent-if",
    deckId: "branching-menu",
    term: "Независимые if",
    exampleCode: 'int score = 59;\nint debts = 1;\nif (score < 60)\n{\n    Console.WriteLine("Низкий балл");\n}\nif (debts > 0)\n{\n    Console.WriteLine("Есть задолженность");\n}',
    exampleResult: "Низкий балл\nЕсть задолженность",
    exampleNote: "Это две отдельные проверки, поэтому выполняются оба блока.",
    kind: "Что выведет код?",
    challengeCode: 'int score = 60;\nint debts = 1;\nif (score < 60)\n{\n    Console.WriteLine("Низкий балл");\n}\nif (debts > 0)\n{\n    Console.WriteLine("Есть задолженность");\n}',
    prompt: "Какие сообщения появятся?",
    options: ["Только «Низкий балл»", "Только «Есть задолженность»", "Оба сообщения", "Ни одного"],
    correctIndex: 1,
    explanation: "Первое условие ложно, второе истинно. Независимые if проверяются по отдельности."
  },
  {
    id: "lab6-condition-order",
    deckId: "branching-menu",
    term: "Порядок проверок",
    exampleCode: 'int score = 95;\nif (score >= 90)\n{\n    Console.WriteLine(5);\n}\nelse if (score >= 75)\n{\n    Console.WriteLine(4);\n}',
    exampleResult: "5",
    exampleNote: "Сначала проверяется высокий порог. Иначе 95 подошло бы и под более широкое условие >= 60.",
    kind: "Что выведет код?",
    challengeCode: 'int score = 95;\nif (score >= 60)\n{\n    Console.WriteLine(3);\n}\nelse if (score >= 90)\n{\n    Console.WriteLine(5);\n}',
    prompt: "Что выведет цепочка с неверным порядком условий?",
    options: ["3", "5", "3 и 5", "Ничего"],
    correctIndex: 0,
    explanation: "95 уже подходит под первое условие >= 60. До ветки с оценкой 5 программа не дойдёт."
  },
  {
    id: "lab6-ternary",
    deckId: "branching-menu",
    term: "Условный оператор ?:",
    exampleCode: 'bool hasDebts = true;\nstring debtStatus = hasDebts ? "Есть задолженности" : "Задолженностей нет";\nConsole.WriteLine(debtStatus);',
    exampleResult: "Есть задолженности",
    exampleNote: "При true выбирается значение до двоеточия, при false — после него.",
    kind: "Что выведет код?",
    challengeCode: 'bool hasDebts = false;\nConsole.WriteLine(hasDebts ? "Есть задолженности" : "Задолженностей нет");',
    prompt: "Какой статус появится в консоли?",
    options: ["Есть задолженности", "Задолженностей нет", "False", "Оба статуса"],
    correctIndex: 1,
    explanation: "Условие равно false, поэтому оператор ?: выбирает выражение после двоеточия."
  },
  {
    id: "lab6-switch",
    deckId: "branching-menu",
    term: "switch",
    exampleCode: 'int action = 2;\nswitch (action)\n{\n    case 1:\n        Console.WriteLine("Данные");\n        break;\n    case 2:\n        Console.WriteLine("Допуск");\n        break;\n    default:\n        Console.WriteLine("Неизвестный пункт меню");\n        break;\n}',
    exampleResult: "Допуск",
    exampleNote: "Значение 2 выбирает case 2. break завершает switch.",
    kind: "Что выведет код?",
    challengeCode: 'int action = 3;\nswitch (action)\n{\n    case 1:\n        Console.WriteLine("Данные");\n        break;\n    case 3:\n        Console.WriteLine("Оценка");\n        break;\n    default:\n        Console.WriteLine("Неизвестный пункт меню");\n        break;\n}',
    prompt: "Какой пункт меню выполнится?",
    options: ["Данные", "Оценка", "Неизвестный пункт меню", "Оба case"],
    correctIndex: 1,
    explanation: "action равно 3, поэтому выполняется case 3 и затем break."
  },
  {
    id: "lab6-default",
    deckId: "branching-menu",
    term: "default",
    exampleCode: 'int action = 9;\nswitch (action)\n{\n    case 1:\n        Console.WriteLine("Данные");\n        break;\n    default:\n        Console.WriteLine("Неизвестный пункт меню");\n        break;\n}',
    exampleResult: "Неизвестный пункт меню",
    exampleNote: "Номер 9 не совпадает ни с одним case, поэтому выполняется default.",
    kind: "Что выведет код?",
    challengeCode: 'int action = 4;\nswitch (action)\n{\n    case 1:\n        Console.WriteLine("Данные");\n        break;\n    default:\n        Console.WriteLine("Неизвестный пункт меню");\n        break;\n}',
    prompt: "Что увидит пользователь?",
    options: ["Данные", "Неизвестный пункт меню", "4", "Ничего"],
    correctIndex: 1,
    explanation: "Для 4 нет подходящего case, поэтому выбирается ветка default."
  },
  {
    id: "lab6-break",
    deckId: "branching-menu",
    term: "break",
    exampleCode: 'int action = 1;\nswitch (action)\n{\n    case 1:\n        Console.WriteLine("Данные");\n        break;\n    default:\n        Console.WriteLine("Неизвестно");\n        break;\n}\nConsole.WriteLine("Готово");',
    exampleResult: "Данные\nГотово",
    exampleNote: "break завершает switch; команда после него продолжает выполняться.",
    kind: "Что выведет код?",
    challengeCode: 'int action = 1;\nswitch (action)\n{\n    case 1:\n        Console.WriteLine("Имя");\n        break;\n    default:\n        Console.WriteLine("Неизвестно");\n        break;\n}\nConsole.WriteLine("Конец");',
    prompt: "Какие строки появятся в консоли?",
    options: ["Только «Имя»", "«Имя», затем «Конец»", "«Имя», затем «Неизвестно»", "Только «Конец»"],
    correctIndex: 1,
    explanation: "break выходит из switch, но не завершает программу. После него выводится «Конец»."
  }
];
