// Each lesson links one glossary term to a worked example and a separate practice question.
const codeLessons = [
  {
    id: "variable",
    deckId: "variables-values",
    term: "Переменная",
    exampleCode: 'int score = 4;\nConsole.WriteLine(score);',
    exampleResult: "4",
    exampleNote: "Имя score позволяет обратиться к сохранённому числу позже.",
    kind: "Что выведет код?",
    challengeCode: 'int lives = 3;\nConsole.WriteLine(lives);',
    prompt: "Что появится в консоли?",
    options: ["3", "lives", "int", "Ничего"],
    correctIndex: 0,
    explanation: "В lives хранится число 3. Console.WriteLine выводит значение переменной, а не её имя."
  },
  {
    id: "initialization",
    deckId: "variables-values",
    term: "Инициализация",
    exampleCode: 'string city = "Казань";\nConsole.WriteLine(city);',
    exampleResult: "Казань",
    exampleNote: "Первое значение задаётся сразу при объявлении переменной.",
    kind: "Найдите строку",
    challengeCode: 'int level;\nlevel = 2;\nConsole.WriteLine(level);',
    prompt: "В какой строке переменная level впервые получает значение?",
    options: ["В первой", "Во второй", "В третьей", "Значение не задано"],
    correctIndex: 1,
    explanation: "В первой строке переменная только объявлена. Первое присваивание происходит во второй строке."
  },
  {
    id: "assignment",
    deckId: "variables-values",
    term: "Присваивание",
    exampleCode: 'int points = 2;\npoints = 5;\nConsole.WriteLine(points);',
    exampleResult: "5",
    exampleNote: "Второе присваивание заменяет прежнее значение points.",
    kind: "Что выведет код?",
    challengeCode: 'int count = 1;\ncount = count + 2;\nConsole.WriteLine(count);',
    prompt: "Что появится в консоли?",
    options: ["1", "2", "3", "12"],
    correctIndex: 2,
    explanation: "Сначала count равен 1. Выражение count + 2 даёт 3, и это значение сохраняется в count."
  },
  {
    id: "int",
    deckId: "csharp-data-types",
    term: "int",
    exampleCode: 'int apples = 6;\nConsole.WriteLine(apples + 2);',
    exampleResult: "8",
    exampleNote: "int хранит целое число; здесь к нему прибавляется ещё 2.",
    kind: "Где ошибка?",
    challengeCode: 'int apples = "6";\nConsole.WriteLine(apples);',
    prompt: "Почему этот код не соберётся?",
    options: ["int нельзя выводить", "Строку нельзя напрямую присвоить int", "Имя apples запрещено", "После 6 нужна точка"],
    correctIndex: 1,
    explanation: "Кавычки делают «6» строкой. Для int нужно записать число без кавычек или явно преобразовать строку."
  },
  {
    id: "bool",
    deckId: "csharp-data-types",
    term: "bool",
    exampleCode: 'bool isReady = true;\nConsole.WriteLine(isReady);',
    exampleResult: "True",
    exampleNote: "bool хранит логическое значение true или false. В консоли оно выводится с прописной буквы.",
    kind: "Что выведет код?",
    challengeCode: 'bool isAdult = 17 >= 18;\nConsole.WriteLine(isAdult);',
    prompt: "Что появится в консоли?",
    options: ["True", "False", "17", "Ошибка компиляции"],
    correctIndex: 1,
    explanation: "17 не больше и не равно 18, поэтому сравнение даёт false; в консоли появится False."
  },
  {
    id: "string",
    deckId: "csharp-data-types",
    term: "string",
    exampleCode: 'string word = "код";\nConsole.WriteLine(word + "ер");',
    exampleResult: "кодер",
    exampleNote: "Оператор + соединяет две строки в одну.",
    kind: "Что выведет код?",
    challengeCode: 'string first = "C";\nstring second = "#";\nConsole.WriteLine(first + second);',
    prompt: "Что появится в консоли?",
    options: ["C#", "C #", "firstsecond", "Ошибка компиляции"],
    correctIndex: 0,
    explanation: "Строки соединяются без пробела: «C» + «#» даёт «C#»."
  },
  {
    id: "decimal",
    deckId: "csharp-data-types",
    term: "decimal",
    exampleCode: 'decimal price = 12.5m;\nConsole.WriteLine(price > 10m);',
    exampleResult: "True",
    exampleNote: "Суффикс m обозначает литерал decimal. Сравнение даёт логический результат.",
    kind: "Где ошибка?",
    challengeCode: 'decimal price = 12.5;\nConsole.WriteLine(price);',
    prompt: "Почему этот код не соберётся?",
    options: ["Для decimal нужен суффикс m у литерала", "decimal нельзя выводить", "Дробные числа запрещены", "Имя price зарезервировано"],
    correctIndex: 0,
    explanation: "Литерал 12.5 без суффикса имеет тип double. Запишите 12.5m для decimal."
  },
  {
    id: "var",
    deckId: "typing-and-output",
    term: "var",
    exampleCode: 'var year = 2026;\nConsole.WriteLine(year);',
    exampleResult: "2026",
    exampleNote: "Компилятор определяет тип int по начальному значению. Тип переменной не меняется потом сам собой.",
    kind: "Где ошибка?",
    challengeCode: 'var count = 5;\ncount = "пять";',
    prompt: "Почему этот код не соберётся?",
    options: ["var нельзя применять с числами", "count уже имеет тип int", "count нельзя изменить", "Нужен Console.WriteLine"],
    correctIndex: 1,
    explanation: "По значению 5 компилятор определил тип int. Строку нельзя напрямую записать в int."
  },
  {
    id: "write-line",
    deckId: "typing-and-output",
    term: "Console.WriteLine",
    exampleCode: 'Console.WriteLine("Первая");\nConsole.WriteLine("Вторая");',
    exampleResult: "Первая\nВторая",
    exampleNote: "Каждый вызов выводит значение и переводит курсор на новую строку.",
    kind: "Что выведет код?",
    challengeCode: 'Console.WriteLine("A");\nConsole.WriteLine("B");',
    prompt: "Как будут расположены буквы в консоли?",
    options: ["A и B на одной строке", "A, затем B на новой строке", "Только B", "Ничего"],
    correctIndex: 1,
    explanation: "После каждого Console.WriteLine курсор переходит на новую строку."
  },
  {
    id: "interpolation",
    deckId: "typing-and-output",
    term: "Строковая интерполяция",
    exampleCode: 'int age = 18;\nConsole.WriteLine($"Возраст: {age}");',
    exampleResult: "Возраст: 18",
    exampleNote: "Знак $ разрешает вставить значение age внутрь строки через фигурные скобки.",
    kind: "Что выведет код?",
    challengeCode: 'string name = "Ира";\nConsole.WriteLine($"Привет, {name}!");',
    prompt: "Что появится в консоли?",
    options: ["Привет, Ира!", "Привет, {name}!", "Привет, name!", "Ошибка компиляции"],
    correctIndex: 0,
    explanation: "Знак $ включает интерполяцию: {name} заменяется значением переменной, то есть «Ира»."
  },
  {
    id: "read-line",
    deckId: "input-operations-conversions",
    term: "Console.ReadLine",
    exampleCode: 'string? name = Console.ReadLine();\nConsole.WriteLine($"Привет, {name}!");',
    exampleInput: "Мира",
    exampleResult: "Привет, Мира!",
    exampleNote: "Console.ReadLine читает введённый текст как строку. Знак ? допускает отсутствие ввода.",
    kind: "Что выведет код?",
    challengeCode: 'string? city = Console.ReadLine();\nConsole.WriteLine($"Город: {city}");',
    challengeInput: "Омск",
    prompt: "Что появится в консоли после ввода?",
    options: ["Город: Омск", "Город: city", "Омск: Город", "Ошибка компиляции"],
    correctIndex: 0,
    explanation: "Console.ReadLine вернёт строку «Омск», а интерполяция подставит её вместо {city}."
  },
  {
    id: "integer-division",
    deckId: "input-operations-conversions",
    term: "Целочисленное деление",
    exampleCode: 'Console.WriteLine(7 / 2);',
    exampleResult: "3",
    exampleNote: "Оба операнда целые, поэтому дробная часть результата отбрасывается.",
    kind: "Что выведет код?",
    challengeCode: 'Console.WriteLine(11 / 4);',
    prompt: "Что появится в консоли?",
    options: ["2", "2.75", "3", "Ошибка компиляции"],
    correctIndex: 0,
    explanation: "11 / 4 при целочисленном делении даёт 2. Дробная часть 0.75 отбрасывается."
  },
  {
    id: "remainder",
    deckId: "input-operations-conversions",
    term: "Остаток от деления",
    exampleCode: 'Console.WriteLine(7 % 2);',
    exampleResult: "1",
    exampleNote: "7 = 2 × 3 + 1, поэтому остаток равен 1.",
    kind: "Что выведет код?",
    challengeCode: 'Console.WriteLine(14 % 5);',
    prompt: "Что появится в консоли?",
    options: ["2", "4", "5", "14"],
    correctIndex: 1,
    explanation: "14 = 5 × 2 + 4. Оператор % возвращает остаток 4."
  },
  {
    id: "explicit-conversion",
    deckId: "input-operations-conversions",
    term: "Явное преобразование",
    exampleCode: 'double value = 4.8;\nint whole = (int)value;\nConsole.WriteLine(whole);',
    exampleResult: "4",
    exampleNote: "Приведение (int) отбрасывает дробную часть положительного числа.",
    kind: "Что выведет код?",
    challengeCode: 'double value = 9.9;\nConsole.WriteLine((int)value);',
    prompt: "Что появится в консоли?",
    options: ["9", "10", "9.9", "Ошибка компиляции"],
    correctIndex: 0,
    explanation: "При приведении 9.9 к int дробная часть отбрасывается, получается 9."
  },
  {
    id: "invalid-input",
    deckId: "input-operations-conversions",
    term: "Некорректный ввод",
    exampleCode: 'string? text = Console.ReadLine();\nif (int.TryParse(text, out int number))\n    Console.WriteLine(number);\nelse\n    Console.WriteLine("Введите число");',
    exampleInput: "кот",
    exampleResult: "Введите число",
    exampleNote: "TryParse проверяет ввод без исключения. Слово «кот» нельзя преобразовать в int.",
    kind: "Что выведет код?",
    challengeCode: 'string? text = Console.ReadLine();\nif (int.TryParse(text, out int number))\n    Console.WriteLine(number);\nelse\n    Console.WriteLine("Ошибка ввода");',
    challengeInput: "12кг",
    prompt: "Что появится в консоли после ввода?",
    options: ["12", "12кг", "Ошибка ввода", "Программа завершится с исключением"],
    correctIndex: 2,
    explanation: "Строка «12кг» целиком не является целым числом. TryParse вернёт false, поэтому выполнится ветка else."
  }
];
